// comingsoon
function comingsoon() {window.open("https://raw.githubusercontent.com/budialim10990/arcade/main/comingsoon.webp");}

// Fishing
function fishin035() {window.open("https://login-fr.onegameslink.com/GameLauncher?casino=driftcasino&clientPlatform=web&clientType=casino&depositUrl=&gameCodeName=fishshr&language=en&lobbyUrl=https%3A%2F%2Flaunch.atlantgaming.com%2Fredirect.html%3Furl%3Dhttps%253A%252F%252Fslot-v-casinoclub.com%252Fpromo%252Fland21%253Fref%253D8f2f3b49f43e3444b03378a6765bf47a&realMode=0");}
function fishin034() {window.open("https://tpg-api.claretfox.com/launch?game_id=PSF-ON-00002&subgame_id=0&return_url=https%3A%2F%2Fwww.livebet.com%2Fhome-redirect.html%3Fredirect_to%3Dhttps%253A%252F%252Flive-bet.com%252Fcasino%252Fcasino_games%253Fproviders%253DPLAYSTAR%2526btag%253D%25252Fcasino%25252Ftable-games%25252Fplaystar%25252Fspicy-fishing&host_id=2c6572b719fbe322fd848fba16328267");}
function fishin033() {window.open("https://tpg-api.claretfox.com/launch?game_id=PSF-ON-00001&subgame_id=0&return_url=https%3A%2F%2Fwww.livebet.com%2Fhome-redirect.html%3Fredirect_to%3Dhttps%253A%252F%252Flive-bet.com%252Fcasino%252Fcasino_games%253Fproviders%253DPLAYSTAR%2526btag%253D%25252Fcasino%25252Ftable-games%25252Fplaystar%25252Fhaidilao&host_id=2c6572b719fbe322fd848fba16328267");}
function fishin032() {window.open("https://tpg-api.claretfox.com/launch?game_id=PSF-ON-00004&subgame_id=0&return_url=https%3A%2F%2Fwww.livebet.com%2Fhome-redirect.html%3Fredirect_to%3Dhttps%253A%252F%252Flive-bet.com%252Fcasino%252Fcasino_games%253Fproviders%253DPLAYSTAR%2526btag%253D%25252Fcasino%25252Ftable-games%25252Fplaystar%25252Ffishing-foodie&host_id=2c6572b719fbe322fd848fba16328267");}
function fishin031() {window.open("https://tpg-api.claretfox.com/launch?game_id=PSF-ON-00003&subgame_id=0&return_url=https%3A%2F%2Fwww.livebet.com%2Fhome-redirect.html%3Fredirect_to%3Dhttps%253A%252F%252Flive-bet.com%252Fcasino%252Fcasino_games%253Fproviders%253DPLAYSTAR%2526btag%253D%25252Fcasino%25252Ftable-games%25252Fplaystar%25252Fzombie-bonus&host_id=2c6572b719fbe322fd848fba16328267");}
function fishin030() {window.open("https://tpg-api.claretfox.com/launch?game_id=PSF-ON-00007&subgame_id=0&return_url=https%3A%2F%2Fwww.livebet.com%2Fhome-redirect.html%3Fredirect_to%3Dhttps%253A%252F%252Flive-bet.com%252Fcasino%252Fcasino_games%253Fproviders%253DPLAYSTAR%2526btag%253D%25252Fcasino%25252Ftable-games%25252Fplaystar%25252Focean-king-s-treasure&host_id=2c6572b719fbe322fd848fba16328267");}
function fishin029() {window.open("https://tpg-api.claretfox.com/launch?game_id=PSF-ON-00005&subgame_id=0&return_url=https%3A%2F%2Fwww.livebet.com%2Fhome-redirect.html%3Fredirect_to%3Dhttps%253A%252F%252Flive-bet.com%252Fcasino%252Fcasino_games%253Fproviders%253DPLAYSTAR%2526btag%253D%25252Fcasino%25252Ftable-games%25252Fplaystar%25252Ffishing-in-thailand&host_id=2c6572b719fbe322fd848fba16328267");}
function fishin028() {window.open("https://tpg-api.claretfox.com/launch?game_id=PSF-ON-00006&subgame_id=0&return_url=https%3A%2F%2Fwww.livebet.com%2Fhome-redirect.html%3Fredirect_to%3Dhttps%253A%252F%252Flive-bet.com%252Fcasino%252Fcasino_games%253Fproviders%253DPLAYSTAR%2526btag%253D%25252Fcasino%25252Ftable-games%25252Fplaystar%25252Ffishing-fa-fa-fa&host_id=2c6572b719fbe322fd848fba16328267");}
function fishin027() {window.open("https://fiweb.cqgame.games/GameRecord/client/AB3/?token=guest&language=en");}
function fishin026() {window.open("https://fiweb.cqgame.games/GameRecord/client/AT05/?token=GUESTPASS&language=zh-cn&dollarsign=Y&app=N&detect=N&language=en");}
function fishin025() {window.open("https://h5bt.cqgame.games/h5/GO02/?token=guest::1000&language=en");}
function fishin024() {window.open("https://www.baoding68c.net/Home/Play/xkqb8q7jdw8oc/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiJ4a3FiOHE3amR3OG9jIiwiZXhwIjoxNzI1NzkzMTk5LCJEYXRhIjoie1wiU2Vzc2lvbk9Db2RlXCI6XCJ4a3FiOHE3amR3OG9jXCIsXCJHYW1lQ29kZVwiOlwiRlNHRlwiLFwiT0NvZGVcIjpudWxsLFwiTGFuZ3VhZ2VcIjpcImlkXCIsXCJSZWRpcmVjdFVybFwiOm51bGwsXCJDcm9zc1wiOm51bGwsXCJQbGF0Zm9ybVwiOm51bGwsXCJPcmlnaW5TZXNzaW9uT0NvZGVcIjpudWxsLFwiQmV0R3JvdXBMZXZlbFwiOm51bGwsXCJEYXRhXCI6bnVsbCxcIkNvbXBldGl0aW9uT0NvZGVcIjpudWxsLFwiRW5hYmxlU3RyZWFtZXJcIjp0cnVlLFwiU2hvd1JhbmtpbmdcIjpmYWxzZSxcIkhpZGVIaXN0b3J5XCI6ZmFsc2UsXCJIaWRlRnVsbFNjcmVlblwiOmZhbHNlfSIsIm5iZiI6MTcyNTc4NTk5OSwiaWF0IjoxNzI1Nzg1OTk5fQ.bPTFaYcHctm_0F7bwQ8yPN-9O1grjp3yLDMp6aUfkPo");}
function fishin023() {window.open("https://www.baoding68c.net/Home/Play/xeyw3p3tdw8oc/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiJ4ZXl3M3AzdGR3OG9jIiwiZXhwIjoxNzI1NzkzMTI2LCJEYXRhIjoie1wiU2Vzc2lvbk9Db2RlXCI6XCJ4ZXl3M3AzdGR3OG9jXCIsXCJHYW1lQ29kZVwiOlwiRlNHRjFcIixcIk9Db2RlXCI6bnVsbCxcIkxhbmd1YWdlXCI6XCJpZFwiLFwiUmVkaXJlY3RVcmxcIjpudWxsLFwiQ3Jvc3NcIjpudWxsLFwiUGxhdGZvcm1cIjpudWxsLFwiT3JpZ2luU2Vzc2lvbk9Db2RlXCI6bnVsbCxcIkJldEdyb3VwTGV2ZWxcIjpudWxsLFwiRGF0YVwiOm51bGwsXCJDb21wZXRpdGlvbk9Db2RlXCI6bnVsbCxcIkVuYWJsZVN0cmVhbWVyXCI6dHJ1ZSxcIlNob3dSYW5raW5nXCI6ZmFsc2UsXCJIaWRlSGlzdG9yeVwiOmZhbHNlLFwiSGlkZUZ1bGxTY3JlZW5cIjpmYWxzZX0iLCJuYmYiOjE3MjU3ODU5MjYsImlhdCI6MTcyNTc4NTkyNn0.83zNg-DQJPgJysDp2kkphZMp19OgNOmKIZr22wUQckE");}
function fishin022() {window.open("https://www.baoding68c.net/Home/Play/xjrixoazth8oc/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiJ4anJpeG9henRoOG9jIiwiZXhwIjoxNzI1NzkzMDYxLCJEYXRhIjoie1wiU2Vzc2lvbk9Db2RlXCI6XCJ4anJpeG9henRoOG9jXCIsXCJHYW1lQ29kZVwiOlwiRkhNQVwiLFwiT0NvZGVcIjpudWxsLFwiTGFuZ3VhZ2VcIjpcImlkXCIsXCJSZWRpcmVjdFVybFwiOm51bGwsXCJDcm9zc1wiOm51bGwsXCJQbGF0Zm9ybVwiOm51bGwsXCJPcmlnaW5TZXNzaW9uT0NvZGVcIjpudWxsLFwiQmV0R3JvdXBMZXZlbFwiOm51bGwsXCJEYXRhXCI6bnVsbCxcIkNvbXBldGl0aW9uT0NvZGVcIjpudWxsLFwiRW5hYmxlU3RyZWFtZXJcIjp0cnVlLFwiU2hvd1JhbmtpbmdcIjpmYWxzZSxcIkhpZGVIaXN0b3J5XCI6ZmFsc2UsXCJIaWRlRnVsbFNjcmVlblwiOmZhbHNlfSIsIm5iZiI6MTcyNTc4NTg2MSwiaWF0IjoxNzI1Nzg1ODYxfQ.dbXD1sfsZiJsA9-n34BF9FJ5uzA2loJBUAjkvRdGfgs");}
function fishin021() {window.open("https://www.baoding68c.net/Home/Play/xjrizsycth8oc/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiJ4anJpenN5Y3RoOG9jIiwiZXhwIjoxNzI1NzkyOTU1LCJEYXRhIjoie1wiU2Vzc2lvbk9Db2RlXCI6XCJ4anJpenN5Y3RoOG9jXCIsXCJHYW1lQ29kZVwiOlwiRmlzaGVybWFuc1doYXJmXCIsXCJPQ29kZVwiOm51bGwsXCJMYW5ndWFnZVwiOlwiaWRcIixcIlJlZGlyZWN0VXJsXCI6bnVsbCxcIkNyb3NzXCI6bnVsbCxcIlBsYXRmb3JtXCI6bnVsbCxcIk9yaWdpblNlc3Npb25PQ29kZVwiOm51bGwsXCJCZXRHcm91cExldmVsXCI6bnVsbCxcIkRhdGFcIjpudWxsLFwiQ29tcGV0aXRpb25PQ29kZVwiOm51bGwsXCJFbmFibGVTdHJlYW1lclwiOnRydWUsXCJTaG93UmFua2luZ1wiOmZhbHNlLFwiSGlkZUhpc3RvcnlcIjpmYWxzZSxcIkhpZGVGdWxsU2NyZWVuXCI6ZmFsc2V9IiwibmJmIjoxNzI1Nzg1NzU1LCJpYXQiOjE3MjU3ODU3NTV9.vVH1ZqtLu4Pg02f95Go5ZTUQHKMqEElGfX65kxdb4Tw");}
function fishin020() {window.open("https://www.gamingworld.net/en/play-game?redirectUrl=http%3A//www.gamingworld.net/games.html&gameID=86");}
function fishin019() {window.open("https://www.baoding68c.net/Home/Play/xm6xy95mth8oc/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiJ4bTZ4eTk1bXRoOG9jIiwiZXhwIjoxNzI1NzkyODQxLCJEYXRhIjoie1wiU2Vzc2lvbk9Db2RlXCI6XCJ4bTZ4eTk1bXRoOG9jXCIsXCJHYW1lQ29kZVwiOlwiRkhCSDVcIixcIk9Db2RlXCI6bnVsbCxcIkxhbmd1YWdlXCI6XCJpZFwiLFwiUmVkaXJlY3RVcmxcIjpudWxsLFwiQ3Jvc3NcIjpudWxsLFwiUGxhdGZvcm1cIjpudWxsLFwiT3JpZ2luU2Vzc2lvbk9Db2RlXCI6bnVsbCxcIkJldEdyb3VwTGV2ZWxcIjpudWxsLFwiRGF0YVwiOm51bGwsXCJDb21wZXRpdGlvbk9Db2RlXCI6bnVsbCxcIkVuYWJsZVN0cmVhbWVyXCI6dHJ1ZSxcIlNob3dSYW5raW5nXCI6ZmFsc2UsXCJIaWRlSGlzdG9yeVwiOmZhbHNlLFwiSGlkZUZ1bGxTY3JlZW5cIjpmYWxzZX0iLCJuYmYiOjE3MjU3ODU2NDEsImlhdCI6MTcyNTc4NTY0MX0.HyzOf-3eq2TtqAYBW6JYNSGjUPHjVfR8kkcoDLJsWlw");}
function fishin018() {window.open("https://www.baoding68c.net/Home/Play/xm6yeqfd8c8oc/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiJ4bTZ5ZXFmZDhjOG9jIiwiZXhwIjoxNzI1NzkxOTY1LCJEYXRhIjoie1wiU2Vzc2lvbk9Db2RlXCI6XCJ4bTZ5ZXFmZDhjOG9jXCIsXCJHYW1lQ29kZVwiOlwiRmlzaFNwb25nZWJvYlwiLFwiT0NvZGVcIjpudWxsLFwiTGFuZ3VhZ2VcIjpcImlkXCIsXCJSZWRpcmVjdFVybFwiOm51bGwsXCJDcm9zc1wiOm51bGwsXCJQbGF0Zm9ybVwiOm51bGwsXCJPcmlnaW5TZXNzaW9uT0NvZGVcIjpudWxsLFwiQmV0R3JvdXBMZXZlbFwiOm51bGwsXCJEYXRhXCI6bnVsbCxcIkNvbXBldGl0aW9uT0NvZGVcIjpudWxsLFwiRW5hYmxlU3RyZWFtZXJcIjp0cnVlLFwiU2hvd1JhbmtpbmdcIjpmYWxzZSxcIkhpZGVIaXN0b3J5XCI6ZmFsc2UsXCJIaWRlRnVsbFNjcmVlblwiOmZhbHNlfSIsIm5iZiI6MTcyNTc4NDc2NSwiaWF0IjoxNzI1Nzg0NzY1fQ.xgedsggi17h0QMVMkni3pzGAnLg_4wJ8s2DAvwQWtL4");}
function fishin017() {window.open("https://www.baoding68c.net/Home/Play/xjrzrgt1nc8oc/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiJ4anJ6cmd0MW5jOG9jIiwiZXhwIjoxNzI1NzkyNzI5LCJEYXRhIjoie1wiU2Vzc2lvbk9Db2RlXCI6XCJ4anJ6cmd0MW5jOG9jXCIsXCJHYW1lQ29kZVwiOlwiRmlzaEh1bnRlckluc2VjdFBhcmFkaXNlXCIsXCJPQ29kZVwiOm51bGwsXCJMYW5ndWFnZVwiOlwiZW5cIixcIlJlZGlyZWN0VXJsXCI6bnVsbCxcIkNyb3NzXCI6bnVsbCxcIlBsYXRmb3JtXCI6bnVsbCxcIk9yaWdpblNlc3Npb25PQ29kZVwiOm51bGwsXCJCZXRHcm91cExldmVsXCI6bnVsbCxcIkRhdGFcIjpudWxsLFwiQ29tcGV0aXRpb25PQ29kZVwiOm51bGwsXCJFbmFibGVTdHJlYW1lclwiOnRydWUsXCJTaG93UmFua2luZ1wiOmZhbHNlLFwiSGlkZUhpc3RvcnlcIjpmYWxzZSxcIkhpZGVGdWxsU2NyZWVuXCI6ZmFsc2V9IiwibmJmIjoxNzI1Nzg1NTI5LCJpYXQiOjE3MjU3ODU1Mjl9.YShGhajVP0VArCOFcoFtio-vjRctOk5i1ZYdD809OgU");}
function fishin016() {window.open("https://www.baoding68c.net/Home/Play/xjrauwctdw8oc/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiJ4anJhdXdjdGR3OG9jIiwiZXhwIjoxNzI1NzkzMzA1LCJEYXRhIjoie1wiU2Vzc2lvbk9Db2RlXCI6XCJ4anJhdXdjdGR3OG9jXCIsXCJHYW1lQ29kZVwiOlwiRlNHRjJcIixcIk9Db2RlXCI6bnVsbCxcIkxhbmd1YWdlXCI6XCJpZFwiLFwiUmVkaXJlY3RVcmxcIjpudWxsLFwiQ3Jvc3NcIjpudWxsLFwiUGxhdGZvcm1cIjpudWxsLFwiT3JpZ2luU2Vzc2lvbk9Db2RlXCI6bnVsbCxcIkJldEdyb3VwTGV2ZWxcIjpudWxsLFwiRGF0YVwiOm51bGwsXCJDb21wZXRpdGlvbk9Db2RlXCI6bnVsbCxcIkVuYWJsZVN0cmVhbWVyXCI6dHJ1ZSxcIlNob3dSYW5raW5nXCI6ZmFsc2UsXCJIaWRlSGlzdG9yeVwiOmZhbHNlLFwiSGlkZUZ1bGxTY3JlZW5cIjpmYWxzZX0iLCJuYmYiOjE3MjU3ODYxMDUsImlhdCI6MTcyNTc4NjEwNX0.l2NEFe8JB6kkZ65hJbdEf6F73RJprClbDaXxtwoZg6E");}
function fishin015() {window.open("https://www.baoding68c.net/Home/Play/qx3o4xrqy95x4/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiJxeDNvNHhycXk5NXg0IiwiZXhwIjoxNzI1NzkzNDEzLCJEYXRhIjoie1wiU2Vzc2lvbk9Db2RlXCI6XCJxeDNvNHhycXk5NXg0XCIsXCJHYW1lQ29kZVwiOlwiRmlzaEh1bnRlckhhcHB5RmlzaDVcIixcIk9Db2RlXCI6bnVsbCxcIkxhbmd1YWdlXCI6XCJlblwiLFwiUmVkaXJlY3RVcmxcIjpudWxsLFwiQ3Jvc3NcIjpudWxsLFwiUGxhdGZvcm1cIjpudWxsLFwiT3JpZ2luU2Vzc2lvbk9Db2RlXCI6bnVsbCxcIkJldEdyb3VwTGV2ZWxcIjpudWxsLFwiRGF0YVwiOm51bGwsXCJDb21wZXRpdGlvbk9Db2RlXCI6bnVsbCxcIkVuYWJsZVN0cmVhbWVyXCI6dHJ1ZSxcIlNob3dSYW5raW5nXCI6ZmFsc2UsXCJIaWRlSGlzdG9yeVwiOmZhbHNlLFwiSGlkZUZ1bGxTY3JlZW5cIjpmYWxzZX0iLCJuYmYiOjE3MjU3ODYyMTMsImlhdCI6MTcyNTc4NjIxM30.Lv9gqjq_ULp9zy_eKcpfbFzUoy-SsHYXZxuGxalfqLs");}
function fishin014() {window.open("https://www.baoding68c.net/Home/Play/xjxnbue5ph8oc/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiJ4anhuYnVlNXBoOG9jIiwiZXhwIjoxNzI1NzkzNjU4LCJEYXRhIjoie1wiU2Vzc2lvbk9Db2RlXCI6XCJ4anhuYnVlNXBoOG9jXCIsXCJHYW1lQ29kZVwiOlwiRmlzaE1vbmV5VHJlZVwiLFwiT0NvZGVcIjpudWxsLFwiTGFuZ3VhZ2VcIjpcImlkXCIsXCJSZWRpcmVjdFVybFwiOm51bGwsXCJDcm9zc1wiOm51bGwsXCJQbGF0Zm9ybVwiOm51bGwsXCJPcmlnaW5TZXNzaW9uT0NvZGVcIjpudWxsLFwiQmV0R3JvdXBMZXZlbFwiOm51bGwsXCJEYXRhXCI6bnVsbCxcIkNvbXBldGl0aW9uT0NvZGVcIjpudWxsLFwiRW5hYmxlU3RyZWFtZXJcIjp0cnVlLFwiU2hvd1JhbmtpbmdcIjpmYWxzZSxcIkhpZGVIaXN0b3J5XCI6ZmFsc2UsXCJIaWRlRnVsbFNjcmVlblwiOmZhbHNlfSIsIm5iZiI6MTcyNTc4NjQ1OCwiaWF0IjoxNzI1Nzg2NDU4fQ.fvWiNZR73eXnCdUiyWItxqbjCDP6a0ZQ94tAvCJt_BQ");}
function fishin013() {window.open("https://www.baoding68c.net/Home/Play/xkqb8yjqph8oc/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiJ4a3FiOHlqcXBoOG9jIiwiZXhwIjoxNzI1NzkzNzE0LCJEYXRhIjoie1wiU2Vzc2lvbk9Db2RlXCI6XCJ4a3FiOHlqcXBoOG9jXCIsXCJHYW1lQ29kZVwiOlwiRmlzaEh1bnRlckJpcmRIdW50ZXJcIixcIk9Db2RlXCI6bnVsbCxcIkxhbmd1YWdlXCI6XCJlblwiLFwiUmVkaXJlY3RVcmxcIjpudWxsLFwiQ3Jvc3NcIjpudWxsLFwiUGxhdGZvcm1cIjpudWxsLFwiT3JpZ2luU2Vzc2lvbk9Db2RlXCI6bnVsbCxcIkJldEdyb3VwTGV2ZWxcIjpudWxsLFwiRGF0YVwiOm51bGwsXCJDb21wZXRpdGlvbk9Db2RlXCI6bnVsbCxcIkVuYWJsZVN0cmVhbWVyXCI6dHJ1ZSxcIlNob3dSYW5raW5nXCI6ZmFsc2UsXCJIaWRlSGlzdG9yeVwiOmZhbHNlLFwiSGlkZUZ1bGxTY3JlZW5cIjpmYWxzZX0iLCJuYmYiOjE3MjU3ODY1MTQsImlhdCI6MTcyNTc4NjUxNH0.py3dqC11duOxGWi4VNLVSkGUZqXFtQkRRphrS31GuN4");}
function fishin012() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/119/6");}
function fishin011() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/1/6");}
function fishin010() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/20/6");}
function fishin009() {window.open("https://wbgame-demo.jiligames.com/212/index.html");}
function fishin008() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/42/6");}
function fishin007() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/74/6");}
function fishin006() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/71/6");}
function fishin005() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/32/6");}
function fishin004() {window.open("https://go.fastspindemo.com?game=F-FT01&language=en_US&type=web&menumode=off&pm=3");}
function fishin003() {window.open("https://lobbyeur.sgplayfun.com/index.jsp?game=F-AH01&language=en_US&menumode=off&type=web");}
function fishin002() {window.open("https://lobbyeur.sgplayfun.com/index.jsp?game=F-SF02&language=en_US&menumode=off&type=web");}
function fishin001() {window.open("https://lobbyeur.sgplayfun.com/index.jsp?game=F-SF01&language=en_US&menumode=off&type=web");}

// Navbar
function fishincad1() {window.open("https://prelive-gs1.pragmaticplaylive.net/api/bigBassDemo");}
function fishincad2() {window.open("https://prelive-gs1.pragmaticplaylive.net/api/spacemanDemo");}
function fishincad3() {window.open("https://redirector3.valueactive.eu/Casino/Default.aspx?applicationid=1023&theme=quickfiressl&usertype=5&sext1=demo&sext2=demo&csid=1867&serverid=1867&variant=MAL-Demo&gameid=flyXDesktop&ul=en");}
function fishincad4() {window.open("https://m13.ns86.kingmakergames.co/games/horse-racing/index.html?lang=en");}
function fishincad5() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/163/6");}
function fishincad6() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/235/6");}
function fishincad7() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/179/6");}
function fishincad8() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/174/6");}
function fishincad9() {window.open("https://h5bt.cqgame.games/h5/GO01/?language=en&token=guest123");}
function fishincad10() {window.open("https://download.iplaystar.net/PSM-ON-00002/?access_token=(*--)6e72982bb3f9da8cce7650cde97b53c1&lang=eng&ccy=NON&sm=00&subid=0&fullscr=1&lc=en-US&pm=1&ns=0&origin=https%3a%2f%2fdemo-api.iplaystar.net&anal=10&lb=1&stf=0&showver=1");}
function fishincad11() {window.open("https://download.iplaystar.net/PSM-ON-00001/?access_token=(*--)6e72982bb3f9da8cce7650cde97b53c1&lang=eng&ccy=NON&sm=00&subid=0&fullscr=1&lc=en-US&pm=1&ns=0&origin=https%3a%2f%2fdemo-api.iplaystar.net&anal=10&lb=1&stf=0&showver=1");}
function fishincad12() {window.open("https://download.iplaystar.net/PSM-ON-00003/?access_token=(*--)6e72982bb3f9da8cce7650cde97b53c1&lang=eng&ccy=NON&sm=00&subid=0&fullscr=1&lc=en-US&pm=1&ns=0&origin=https%3a%2f%2fdemo-api.iplaystar.net&anal=10&lb=1&stf=0&showver=1");}
function fishincad13() {window.open("https://download.iplaystar.net/PSM-ON-00008/?access_token=(*--)6e72982bb3f9da8cce7650cde97b53c1&lang=eng&ccy=NON&sm=00&subid=0&fullscr=1&lc=en-US&pm=1&ns=0&origin=https%3a%2f%2fdemo-api.iplaystar.net&anal=10&lb=1&stf=0&showver=1");}
function fishincad14() {window.open("link");}

// casino
function casin1() {window.open("https://m13.ns86.kingmakergames.co/games/bonus-dice/index.html?lang=en");}
function casin2() {window.open("https://m13.ns86.kingmakergames.co/games/bingo/index.html?lang=en");}
function casin3() {window.open("https://thestartuptoday.com/iframe/bola-golek-by-kingmaker.html");}
function casin4() {window.open("https://lobby.sgplayfun.com?game=C-SD01&language=en_US&type=web&menumode=off/");}
function casin5() {window.open("https://lobby.sgplayfun.com/touch/spadenew/20201101B/games/belangkai/index.jsp?menumode=off&game=C-BK01&language=en_US&type=web");}
function casin6() {window.open("https://lobby.sgplayfun.com/touch/spadenew/20201101B/games/fishprawncrab/index.jsp?menumode=off&game=C-TF02&language=en_US&type=web");}
function casin7() {window.open("https://redirector32.valueactive.eu/Casino/Default.aspx?applicationid=4023&sext1=demo&sext2=demo&serverid=22619&gameid=realRouletteWithCarolineDesktop&ul=en&variant=UAT-demo");}
function casin8() {window.open("https://redirector32.valueactive.eu/Casino/Default.aspx?applicationid=4023&sext1=demo&sext2=demo&serverid=22619&gameid=realDealerRouletteDealerSaratiDesktop&ul=en&variant=UAT-demo");}
function casin9() {window.open("https://staticpff.yggdrasilgaming.com/init/launchClient.html?gameid=22001");}
function casin10() {window.open("https://lobby.sgplayfun.com?game=C-RT01&language=en_US&type=web&menumode=off/");}
function casin11() {window.open("https://cachedownload.playtechone.com/ngmdesktop/casinoclient.html?game=dbro&preferedmode=offline");}
function casin12() {window.open("https://cachedownload.playtechone.com/ngmdesktop/casinoclient.html?game=db1000ro&preferedmode=offline");}
function casin13() {window.open("https://netent-static.casinomodule.com/games/europeanroulette3_mobile_html/game/europeanroulette3_mobile_html.xhtml?staticServer=https%3A%2F%2Fnetent-static.casinomodule.com%2F&targetElement=netentgame&flashParams.bgcolor=000000&gameId=europeanroulette3_not_mobile&mobileParams.lobbyURL=https%253A%252F%252Fgames.netent.com%252Ftable-games%252Feuropean-roulette-slot%252F&server=https%3A%2F%2Fnetent-game.casinomodule.com%2F&lang=en&sessId=DEMO-5394227742-EUR&operatorId=default");}
function casin14() {window.open("https://h5c.cqgame.games/213/?language=en&token=guest");}
function casin15() {window.open("https://h5c.cqgame.games/207/?language=en&token=guest123");}
function casin16() {window.open("https://cachedownload.playtechone.com/ngmdesktop/casinoclient.html?game=mro&preferedmode=offline");}
function casin17() {window.open("https://m13.ns86.kingmakergames.co/games/viet-fish-prawn-crab/index.html?lang=en");}
function casin18() {window.open("https://democasino.betsoftgaming.com/cwguestlogin.do?bankId=675&CDN=AUTO&gameId=10");}
function casin19() {window.open("https://demo-ng.nucleusgaming.com/cwguestlogin.do?bankId=167&lang=en&gameId=30265");}
function casin20() {window.open("https://crapswin.blogspot.com/2023/08/craps.html");}
function casin21() {window.open("https://asccw.playngonetwork.com/casino/ContainerLauncher?pid=2&gid=craps&lang=en_GB&practice=1&channel=desktop&demo=2");}
function casin22() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/152/6");}
function casin23() {window.open("https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?gameSymbol=bca&websiteUrl=https%3A%2F%2Fdemogamesfree.pragmaticplay.net&jurisdiction=99&lobby_url=https%3A%2F%2Fwww.pragmaticplay.com%2Fen%2F&lang=EN&cur=USD");}
function casin24() {window.open("https://app-test.insvr.com/games/?brandid=a9d542ac-c9bb-e311-93f6-80c16e0883f4&keyname=Baccarat3HZC&mode=fun&locale=en&lobbyurl=https%3a%2f%2fhaba88.com%2f");}
function casin25() {window.open("https://app-test.insvr.com/games/?brandid=a9d542ac-c9bb-e311-93f6-80c16e0883f4&keyname=SicBo&mode=fun&locale=en&lobbyurl=https%3a%2f%2fhaba88.com%2f");}
function casin26() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/125/6");}
function casin27() {window.open("https://app-test.insvr.com/games/?brandid=a9d542ac-c9bb-e311-93f6-80c16e0883f4&keyname=TGDragonTiger&mode=fun&locale=en&lobbyurl=https%3a%2f%2fhaba88.com%2f%3fref%3dlang");}
function casin28() {window.open("https://bgaming-network.com/play/HiLoSwitch/FUN?server=demo");}
function casin29() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/233/6");}
function casin30() {window.open("https://redirector32.valueactive.eu/Casino/Default.aspx?applicationid=4023&sext1=demo&sext2=demo&serverid=22619&gameid=ultimateBlackjackwithOliviaDesktop&ul=en&variant=UAT-demo");}
function casin31() {window.open("https://redirector32.valueactive.eu/Casino/Default.aspx?applicationid=4023&sext1=demo&sext2=demo&serverid=22619&gameid=ultimateBlackjackWithRachaelDesktop&ul=en&variant=UAT-demo");}
function casin32() {window.open("https://playsonsite-dgm.ps-gamespace.com/launch?key=TEST550004&partner=playsonsite-prod&gameName=blackjack_us_high&lang=en&wl=pl_gate");}
function casin33() {window.open("https://www.funkygames.io/demo?gameCode=602826&lang=en");}
function casin34() {window.open("https://pg.pascalgaming.com/?partnerId=18746949&currency=USD&lan=en&gameId=61&mode=fun");}
function casin35() {window.open("https://demo.evoplay.games/demo/table/html5/evoplay/indianpoker");}
function casin36() {window.open("https://demo.talentainternational.com/launch/launch.jsp?types=card.txsholdem&lang=en&currency=FUN&otp=guest&closeOnExit=1&enableClose=0");}
function casin37() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/111/6");}
function casin38() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/113/6");}
function casin39() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/94/6");}
function casin40() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/161/6");}
function casin41() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/72/6");}
function casin42() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/124/6");}
function casin43() {window.open("https://jiligames.com/plusplayer/PlusTrialWeb/197/6");}
function casin44() {window.open("link");}

// Boongo
function Boong1() {window.open("https://bng.games/play/black_wolf/");}
function Boong2() {window.open("https://bng.games/play/grab_the_gold/");}
function Boong3() {window.open("https://bng.games/play/african_spirit_sticky_wilds/");}
function Boong4() {window.open("https://bng.games/play/3_hot_chillies/");}
function Boong5() {window.open("https://bng.games/play/777_coins/");}
function Boong6() {window.open("https://bng.games/play/green_chilli_2/");}
function Boong7() {window.open("https://3oaks.com/api/v1/games/tiger_jungle/play?lang=en");}
function Boong8() {window.open("https://3oaks.com/api/v1/games/hit_the_gold/play?lang=en");}
function Boong9() {window.open("https://3oaks.com/api/v1/games/queen_of_the_sun/play?lang=en");}
function Boong10() {window.open("https://3oaks.com/api/v1/games/sun_of_egypt_2/play?lang=en");}
function Boong11() {window.open("https://3oaks.com/api/v1/games/super_rich_god/play?lang=en");}
function Boong12() {window.open("https://3oaks.com/api/v1/games/magic_apple/play?lang=en");}
function Boong13() {window.open("https://3oaks.com/api/v1/games/15_dragon_pearls/play?lang=en");}
function Boong14() {window.open("https://3oaks.com/api/v1/games/wolf_saga/play?lang=en");}
function Boong15() {window.open("https://booongo.com/play/ganesha_boost/?lang=en");}
function Boong16() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:slot&lang=en&mobile=0&game=aztec_fire");}
function Boong17() {window.open("https://booongo.com/play/wolf_night/?lang=en");}
function Boong18() {window.open("https://booongo.com/play/3_coins_egypt/?lang=en");}
function Boong19() {window.open("https://booongo.com/play/wukong/?lang=en");}
function Boong20() {window.open("https://booongo.com/play/scarab_boost/?lang=en");}
function Boong21() {window.open("https://booongo.com/play/3_coins/?lang=en");}
function Boong22() {window.open("https://3oaks.com/api/v1/games/dragon_pearls/play?lang=en");}
function Boong23() {window.open("https://3oaks.com/api/v1/games/sun_of_egypt/play?lang=en");}
function Boong24() {window.open("https://3oaks.com/api/v1/games/thunder_of_olympus/play?lang=en");}
function Boong25() {window.open("https://3oaks.com/api/v1/games/great_panda/play?lang=en");}
function Boong26() {window.open("https://3oaks.com/api/v1/games/buddha_fortune/play?lang=en");}
function Boong27() {window.open("https://booongo.com/play/tigers_gold/?lang=en&mobile=0");}
function Boong28() {window.open("https://3oaks.com/api/v1/games/aztec_sun/play?lang=en");}
function Boong29() {window.open("https://3oaks.com/api/v1/games/scarab_temple/play?lang=en");}
function Boong30() {window.open("https://3oaks.com/api/v1/games/moon_sisters/play?lang=en");}
function Boong31() {window.open("https://3oaks.com/api/v1/games/super_marble/play?lang=en");}
function Boong32() {window.open("https://3oaks.com/api/v1/games/tiger_stone/play?lang=en");}
function Boong33() {window.open("https://booongo.com/play/magic_ball/?lang=en");}
function Boong34() {window.open("https://3oaks.com/api/v1/games/book_of_sun_choice/play?lang=en");}
function Boong35() {window.open("https://3oaks.com/api/v1/games/scarab_riches/play?lang=en");}
function Boong36() {window.open("https://3oaks.com/api/v1/games/olympian_gods/play?lang=en");}
function Boong37() {window.open("https://3oaks.com/api/v1/games/book_of_sun/play?lang=en");}
function Boong38() {window.open("https://booongo.com/play/book_of_sun_multichance/");}
function Boong39() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:777_gems-1485033434071@booongo.com&game=777_gems&lang=en&mobile=0");}
function Boong40() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:777_gems_respin-1485033434071@booongo.com&game=777_gems_respin&lang=en&mobile=0");}
function Boong41() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:black_wolf-1485033434071@booongo.com&game=black_wolf&lang=en&mobile=0");}
function Boong42() {window.open("https://booongo.com/play/happy_fish/");}
function Boong43() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:candy_boom-1485033434071@booongo.com&game=candy_boom&lang=en&mobile=0");}
function Boong44() {window.open("https://3oaks.com/api/v1/games/sun_of_egypt_3/play?lang=en");}
function Boong45() {window.open("https://booongo.com/play/caishen_wealth/");}
function Boong46() {window.open("https://3oaks.com/api/v1/games/pearl_diver_2/play?lang=en");}
function Boong47() {window.open("https://booongo.com/play/gold_express/?lang=en");}
function Boong48() {window.open("https://booongo.com/play/golden_dancing_lion/?lang=en");}
function Boong49() {window.open("https://booongo.com/play/lord_fortune_2/?lang=en");}
function Boong50() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:book_of_wizard_crystal-1485033434071@booongo.com&game=book_of_wizard_crystal&lang=en&mobile=0");}
function Boong51() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:little_farm-1485033434071@booongo.com&game=little_farm&lang=en&desktop=0");}
function Boong52() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:forest_spirit-1485033434071@booongo.com&game=forest_spirit&lang=en&mobile=0");}
function Boong53() {window.open("https://booongo.com/play/lady_fortune/");}
function Boong54() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:mummy_power-1485033434071@booongo.com&game=mummy_power&lang=en&mobile=0");}
function Boong55() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:tiger_gems-1485033434071@booongo.com&game=tiger_gems&lang=en&mobile=0");}
function Boong56() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:grab_the_gold-1485033434071@booongo.com&game=grab_the_gold&lang=en&mobile=0");}
function Boong57() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:more_magic_apple-1485033434071@booongo.com&game=more_magic_apple&lang=en&mobile=0");}
function Boong58() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:egypt_fire-1485033434071@booongo.com&game=egypt_fire&lang=en&mobile=0");}
function Boong59() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:yo_ho_gold-1485033434071@booongo.com&game=yo_ho_gold&lang=en&mobile=0");}
function Boong60() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:maya_sun-1485033434071@booongo.com&game=maya_sun&lang=en&mobile=0");}
function Boong61() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:boom_gold-1485033434071@booongo.com&game=boom_gold&lang=en&mobile=0");}
function Boong62() {window.open("https://3oaks.com/api/v1/games/dragon_wealth/play?lang=en");}
function Boong63() {window.open("https://booongo.com/play/sunlight_princess");}
function Boong64() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:goddess_of_egypt-1485033434071@booongo.com&game=goddess_of_egypt&lang=en&mobile=0");}
function Boong65() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:rio_gems-1485033434071@booongo.com&game=rio_gems&lang=en&mobile=0");}
function Boong66() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:hit_more_gold-1485033434071@booongo.com&game=hit_more_gold&lang=en&mobile=0");}
function Boong67() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:sticky_piggy-1485033434071@booongo.com&game=sticky_piggy&lang=en&mobile=0");}
function Boong68() {window.open("https://booongo.com/play/green_chilli/?lang=en");}
function Boong69() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:big_heist-1485033434071@booongo.com&game=big_heist&lang=en&mobile=0");}
function Boong70() {window.open("https://demobox.betsrv.com/booongo.com/static/game.html?profile=default&wl=demo&sound=1&title=&token=test:lotus_charm-1485033434071@booongo.com&game=lotus_charm&lang=en&mobile=0");}
function Boong71() {window.open("https://booongo.com/play/eggs_of_gold/");}
function Boong72() {window.open("https://booongo.com/play/king_of_heroes/?lang=en");}
function Boong73() {window.open("https://booongo.com/play/magic_apple_2/");}
function Boong74() {window.open("https://raw.githubusercontent.com/budialim10990/arcade/main/comingsoon.webp");}
function Boong75() {window.open("https://booongo.com/play/book_of_wizard/");}
function Boong76() {window.open("https://booongo.com/play/pearl_diver/");}
function Boong77() {window.open("https://booongo.com/play/eye_of_gold/");}
function Boong78() {window.open("https://booongo.com/play/15_golden_eggs/");}
function Boong79() {window.open("https://booongo.com/play/gods_temple_deluxe/");}
function Boong80() {window.open("https://raw.githubusercontent.com/budialim10990/arcade/main/comingsoon.webp");}
function Boong81() {window.open("https://raw.githubusercontent.com/budialim10990/arcade/main/comingsoon.webp");}
function Boong82() {window.open("https://raw.githubusercontent.com/budialim10990/arcade/main/comingsoon.webp");}
function Boong83() {window.open("link");}
